Updated to jenkins 2.60.3
Bumping up the Jenkins version to avoid this message:

Failed Loading plugin Pipeline: Nodes and Processes v2.17 (workflow-durable-task-step)
    java.io.IOException: Pipeline: Nodes and Processes v2.17 failed to load.
    - You must update Jenkins from v2.60.2 to v2.60.3 or later to run this plugin.
    at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:626)
    at hudson.PluginManager$2$1$1.run(PluginManager.java:516)
    at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
    at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
    at jenkins.model.Jenkins$7.runTask(Jenkins.java:1090)
    at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
    at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)